name: Build and deploy

on:
  push:
    branches: "*"
    paths-ignore:
      - 'README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up SSH key
        run: |
          eval "$(ssh-agent -a /tmp/ssh_agent.sock)"
          ssh-add - <<< "${{ secrets.CLOUD9_DEPLOY_KEY }}"

      # https://github.com/docker/build-push-action/issues/321#issuecomment-819897120
      - name: Remove dotnet
        run: sudo rm -rf /usr/share/dotnet

      - name: Build and push to local registry
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          tags: cs50/ide:${{ github.sha }},cs50/ide:latest
          ssh: default
          build-args: |
            GITHUB_SHA=${{ github.sha }}
          load: true

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          # Upload static assets to CDN
          docker cp "$(docker create cs50/ide:${{ github.sha }})":/opt/c9/packages/cs50/cdn .
          aws s3 cp --recursive cdn/ "s3://mirror.cs50.net/ide/${{ github.sha }}/"

          # Push Docker image
          docker push cs50/ide:${{ github.sha }}
          docker push cs50/ide:latest
